{
 "title": "Green",
 "description": "A Filecoin lotus dashboard for miners",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "location_name",
    "label": "Location",
    "query": {
     "query": "query_result(sort(green_rack_power_consumption_va))"
    }
   },
   {
    "name": "miner_id",
    "label": "Miner ID",
    "query": {
     "query": "label_values(lotus_miner_info,miner_id)"
    }
   },
   {
    "name": "worker_host",
    "label": "Worker",
    "query": {
     "query": "query_result(sort(lotus_miner_worker_cpu{miner_id=\"$miner_id\"}))"
    }
   },
   {
    "name": "client_name",
    "label": "Client Name",
    "query": {
     "query": "query_result(sort(green_rack_power_consumption_va{}))"
    }
   },
   {
    "name": "rack_id",
    "label": "Rack Id",
    "query": {
     "query": "query_result(sort(green_rack_power_consumption_va{client_name=\"$client_name\"}))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Datacenter - $localtion_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "location_name",
   "collapsed": true
  },
  {
   "title": "Site consumption - $location_name",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "targets": [
    {
     "expr": "green_rack_power_consumption_va{location_name=\"$location_name\"}",
     "legendFormat": "Grid consumption"
    }
   ]
  },
  { "title": "Client - $client_name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }, "repeat": "client_name" },
  {
   "title": "Rack consumption - $client_name",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "targets": [
    {
     "expr": "sum(green_rack_power_consumption_va{client_name=\"$client_name\"}) by (rack_id)",
     "legendFormat": "Rack-{{rack_id}}"
    }
   ]
  },
  { "title": "Racks  (Id=$rack_id)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 }, "repeat": "rack_id" },
  {
   "title": "Rack consumption",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "targets": [
    {
     "expr": "green_rack_power_consumption_va - on() sum(green_equipment_power_consumption_va)",
     "legendFormat": "Shared equipment"
    },
    {
     "expr": "sum(green_equipment_power_consumption_va) by (in_scope)",
     "legendFormat": "{{in_scope}}"
    },
    {
     "expr": "green_rack_power_consumption_va",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Equipment list",
   "type": "table",
   "gridPos": { "h": 16, "w": 9, "x": 14, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "targets": [
    {
     "expr": "green_equipment_power_consumption_va{rack_id=\"$rack_id\"}",
     "legendFormat": "{{equipment}}"
    },
    {
     "expr": "green_equipment_power_consumption_va{rack_id=\"$rack_id\"} * on() group_left () (green_rack_power_consumption_va{rack_id=\"$rack_id\"} / on() sum(green_equipment_power_consumption_va{rack_id=\"$rack_id\"}))",
     "legendFormat": "__auto"
    },
    {
     "expr": "green_equipment_power_consumption_va * on() group_left () (green_rack_power_consumption_va / on() sum(green_equipment_power_consumption_va)) / on(equipment)  group_left()  (sum(green_sector_resource) by (equipment))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Equipment consumption",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "targets": [
    {
     "expr": "green_equipment_power_consumption_va{rack_id=\"$rack_id\"}",
     "legendFormat": "{{equipment}}"
    }
   ]
  },
  { "title": "Miner - $miner_id", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 }, "repeat": "miner_id" },
  {
   "title": "Sector Consumption",
   "type": "table",
   "gridPos": { "h": 16, "w": 9, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "targets": [
    {
     "expr": "sort_desc(sum(green_sector_resource{miner_id=\"$miner_id\"} * on(equipment) group_left () (green_equipment_power_consumption_va * on() group_left () (green_rack_power_consumption_va / on() sum(green_equipment_power_consumption_va)) / on(equipment) (sum(green_sector_resource) by (equipment)))) by (sector_id))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Chain (Filscan)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Data Height",
   "type": "stat",
   "description": "curl -X POST https://api-v2.filscan.io/api/v1/TotalIndicators --data '{}'|jq .",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "body": "{}",
     "cacheDurationSeconds": 300,
     "fields": [
      {
       "jsonPath": "$.result.total_indicators.latest_height",
       "name": "",
       "type": "number"
      }
     ],
     "method": "POST",
     "urlPath": "/api/v1/TotalIndicators"
    }
   ]
  },
  {
   "title": "Avg msgs",
   "type": "stat",
   "description": "Average messages per tipset",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "msgs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "body": "{}",
     "cacheDurationSeconds": 300,
     "fields": [
      {
       "jsonPath": "$.result.total_indicators.avg_message_count",
       "name": "",
       "type": "number"
      }
     ],
     "method": "POST",
     "urlPath": "/api/v1/TotalIndicators"
    }
   ]
  },
  {
   "title": "Avg Blocks",
   "type": "stat",
   "description": "Average blocks per tipset",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "blocks" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "body": "{}",
     "cacheDurationSeconds": 300,
     "fields": [
      {
       "jsonPath": "$.result.total_indicators.avg_block_count",
       "name": "",
       "type": "number"
      }
     ],
     "method": "POST",
     "urlPath": "/api/v1/TotalIndicators"
    }
   ]
  },
  {
   "title": "Active miners",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "miners" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "body": "{}",
     "cacheDurationSeconds": 300,
     "fields": [
      {
       "jsonPath": "$.result.total_indicators.active_miners",
       "name": "",
       "type": "number"
      }
     ],
     "method": "POST",
     "urlPath": "/api/v1/TotalIndicators"
    }
   ]
  },
  {
   "title": "Network QaP",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "body": "{}",
     "cacheDurationSeconds": 300,
     "fields": [
      {
       "jsonPath": "$.result.total_indicators.total_quality_power",
       "name": "",
       "type": "number"
      }
     ],
     "method": "POST",
     "urlPath": "/api/v1/TotalIndicators"
    }
   ]
  },
  {
   "title": "Var QaP 24H",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "body": "{}",
     "cacheDurationSeconds": 300,
     "fields": [
      {
       "jsonPath": "$.result.total_indicators.power_increase_24h",
       "name": "",
       "type": "number"
      }
     ],
     "method": "POST",
     "urlPath": "/api/v1/TotalIndicators"
    }
   ]
  },
  {
   "title": "Reward",
   "type": "stat",
   "description": "24H Fil per TiB reward",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "Fil/TiB" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "body": "{}",
     "cacheDurationSeconds": 300,
     "fields": [
      {
       "jsonPath": "$.result.total_indicators.fil_per_tera_24h",
       "name": "",
       "type": "number"
      }
     ],
     "method": "POST",
     "urlPath": "/api/v1/TotalIndicators"
    }
   ]
  },
  {
   "title": "Block Reward",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "Fil" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "body": "{}",
     "cacheDurationSeconds": 300,
     "fields": [
      {
       "jsonPath": "$.result.total_indicators.win_count_reward",
       "name": "",
       "type": "number"
      }
     ],
     "method": "POST",
     "urlPath": "/api/v1/TotalIndicators"
    }
   ]
  },
  {
   "title": "Sector Pledge",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "Fil/TiB" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "body": "{}",
     "cacheDurationSeconds": 300,
     "fields": [
      {
       "jsonPath": "$.result.total_indicators.miner_initial_pledge",
       "name": "",
       "type": "number"
      }
     ],
     "method": "POST",
     "urlPath": "/api/v1/TotalIndicators"
    }
   ]
  },
  {
   "title": "32G sector gas",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "Fil/TiB" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "body": "{}",
     "cacheDurationSeconds": 300,
     "fields": [
      {
       "jsonPath": "$.result.total_indicators.gas_in_32g",
       "name": "",
       "type": "number"
      }
     ],
     "method": "POST",
     "urlPath": "/api/v1/TotalIndicators"
    }
   ]
  },
  {
   "title": "Main",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "(${__to}/1000 - 1598306400)/ 30",
     "type": "math"
    },
    {
     "expr": "lotus_chain_height{miner_id=\"$miner_id\"}",
     "legendFormat": "Chain Head"
    },
    { "expression": "$NodeEpoch-$CurrentEpoch", "type": "math" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_info{miner_id=\"$miner_id\"}"
    }
   ]
  },
  {
   "title": "Daemon Version",
   "type": "table",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "lotus_info{miner_id=\"$miner_id\"}"
    }
   ]
  },
  {
   "title": "Miner Version",
   "type": "table",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "lotus_miner_info{miner_id=\"$miner_id\"}"
    }
   ]
  },
  {
   "title": "Sealing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Sealing jobs All (Running VS Idle)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "# REtourne le nombre de JOB dans l'etat running\nlabel_replace(count by (task) (lotus_miner_worker_job{miner_id=\"$miner_id\",run_wait=\"0\"}),\"task\",\"running_$1\",\"task\",\"(.*)\")",
     "legendFormat": "{{ task }}"
    },
    {
     "expr": "label_replace(count by (state) (lotus_miner_sector_state{miner_id=\"$miner_id\", state!~\"(Proving|Removed|Available)\"} unless on (sector_id) lotus_miner_worker_job{miner_id=\"$miner_id\",run_wait=\"0\"}),\"state\",\"not_running_$1\",\"state\",\"(.*)\")",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "IDLE Sealing Sectors",
   "type": "table",
   "gridPos": { "h": 20, "w": 7, "x": 10, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "# Retourne tout les secteurs qui sont sur les workers mais dans un statut different de Running. On les enrichis avec les infos des workers (Assigned par exemple)\n(lotus_miner_sector_state{miner_id=\"$miner_id\", state!~\"(Proving|Removed|Available|UpdateActivating)\"} * on (sector_id) group_left(job_id,run_wait,job_start_time,task,worker) lotus_miner_worker_job{miner_id=\"$miner_id\", run_wait!=\"0\"})*1"
    }
   ]
  },
  {
   "title": "RUNNING Sealing Sectors",
   "type": "table",
   "gridPos": { "h": 20, "w": 7, "x": 17, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "lotus_miner_worker_job{miner_id=\"$miner_id\",run_wait=\"0\"}"
    },
    {
     "expr": "# Calcul do 95 centile sur 30 jours des jobs par Worker et Par task et calcul le temps restant pour chacun des jobs\nlotus_miner_worker_job{miner_id=\"$miner_id\",run_wait=\"0\"} - on(worker_host,task) group_left()(quantile(0.95,(max_over_time(lotus_miner_worker_job{miner_id=\"$miner_id\",worker_host!=\"\", run_wait=\"0\"}[30d]) > 1)) by (worker_host,task))"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Sectors By State",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count by (state) (lotus_miner_sector_state{miner_id=\"$miner_id\"})",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "count(lotus_miner_sector_state{state=\"Proving\", miner_id=\"$miner_id\"} unless on (sector_id) lotus_miner_deadline_active_partition_sector{miner_id=\"$miner_id\"})",
     "legendFormat": "Expired"
    },
    {
     "expr": "count(lotus_miner_sector_state{miner_id=\"$miner_id\", to_upgrade=\"True\" })",
     "legendFormat": "To Upgrade"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count (lotus_miner_worker_cpu{miner_id=\"$miner_id\"})",
     "legendFormat": "Number of Workers"
    }
   ]
  },
  {
   "title": "Average Sealing time",
   "type": "table",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "targets": [
    {
     "expr": "# Calcul do 95 centile sur 30 jours\nquantile(0.95,(max_over_time(lotus_miner_worker_job{miner_id=\"$miner_id\", worker_host!=\"\", run_wait=\"0\"}[30d]) > 1)) by (worker_host,task)",
     "legendFormat": "{{ legend }} - {{ worker_host }}"
    },
    {
     "expr": "# Calcul do 95 centile sur 2 jours\nquantile(0.95,(max_over_time(lotus_miner_worker_job{miner_id=\"$miner_id\", worker_host!=\"\", run_wait=\"0\"}[2d]) > 1)) by (worker_host,task)",
     "legendFormat": "{{ legend }} - {{ worker_host }}"
    }
   ]
  },
  {
   "title": "Workers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Resources - $worker_host",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4.8, "x": 0, "y": 78 },
   "repeat": "worker_host",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg((lotus_miner_worker_cpu_used{miner_id=\"$miner_id\", worker_host=\"$worker_host\"})/(lotus_miner_worker_cpu{miner_id=\"$miner_id\", worker_host=\"$worker_host\"}) >= 0)",
     "legendFormat": "CPU"
    },
    {
     "expr": "avg((lotus_miner_worker_gpu_used{miner_id=\"$miner_id\", worker_host=\"$worker_host\"})/(lotus_miner_worker_gpu{miner_id=\"$miner_id\", worker_host=\"$worker_host\"}) >= 0)",
     "legendFormat": "GPU"
    },
    {
     "expr": "avg((lotus_miner_worker_ram_tasks{miner_id=\"$miner_id\", worker_host=\"$worker_host\"}+lotus_miner_worker_ram_reserved{miner_id=\"$miner_id\", worker_host=\"$worker_host\"})/(lotus_miner_worker_ram_total{miner_id=\"$miner_id\", worker_host=\"$worker_host\"}) >= 0)",
     "legendFormat": "RAM"
    },
    {
     "expr": "avg((lotus_miner_worker_vmem_tasks{miner_id=\"$miner_id\", worker_host=\"$worker_host\"}+lotus_miner_worker_vmem_reserved{miner_id=\"$miner_id\", worker_host=\"$worker_host\"})/(lotus_miner_worker_vmem_total{miner_id=\"$miner_id\", worker_host=\"$worker_host\"}) >= 0)",
     "legendFormat": "VMEM"
    }
   ]
  },
  {
   "title": "Sealing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Sealing jobs - RUNNING",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "# REtourne le nombre de JOB dans l'etat running\ncount by (task) (lotus_miner_worker_job{miner_id=\"$miner_id\",run_wait=\"0\"})",
     "legendFormat": "{{ task }}"
    }
   ]
  },
  {
   "title": "Sealing jobs - IDLE",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count by (state) ((lotus_miner_sector_state{miner_id=\"$miner_id\", state!~\"(Proving|Removed|Available)\"}) unless on (sector_id) lotus_miner_worker_job{miner_id=\"$miner_id\",run_wait=\"0\"})",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Sealing ERRORS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count by (state) (lotus_miner_sector_state{miner_id=\"$miner_id\", state!~\"(Available)\" })",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Worker - Ressources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 },
   "repeat": "worker",
   "targets": [
    {}
   ]
  },
  {
   "title": "$worker_host - CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 92 },
   "repeat": "worker_host",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "lotus_miner_worker_cpu_used{miner_id=\"$miner_id\", worker_host=\"$worker_host\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "lotus_miner_worker_cpu{miner_id=\"$miner_id\", worker_host=\"$worker_host\"}-lotus_miner_worker_cpu_used{miner_id=\"$miner_id\", worker_host=\"$worker_host\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "lotus_miner_worker_cpu{miner_id=\"$miner_id\", worker_host=\"$worker_host\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "$worker_host - GPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 92 },
   "repeat": "worker_host",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "lotus_miner_worker_gpu_used{miner_id=\"$miner_id\", worker_host=\"$worker_host\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "lotus_miner_worker_gpu{miner_id=\"$miner_id\", worker_host=\"$worker_host\"}-lotus_miner_worker_gpu_used{miner_id=\"$miner_id\", worker_host=\"$worker_host\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "lotus_miner_worker_gpu{miner_id=\"$miner_id\", worker_host=\"$worker_host\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "$worker_host - Physical Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 92 },
   "repeat": "worker_host",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "lotus_miner_worker_ram_tasks{miner_id=\"$miner_id\", worker_host=\"$worker_host\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "lotus_miner_worker_ram_reserved{miner_id=\"$miner_id\", worker_host=\"$worker_host\"}",
     "legendFormat": "Reserved"
    },
    {
     "expr": "lotus_miner_worker_ram_total{miner_id=\"$miner_id\", worker_host=\"$worker_host\"}-(lotus_miner_worker_ram_reserved{miner_id=\"$miner_id\", worker_host=\"$worker_host\"}+lotus_miner_worker_ram_tasks{miner_id=\"$miner_id\", worker_host=\"$worker_host\"})",
     "legendFormat": "Free"
    },
    {
     "expr": "lotus_miner_worker_ram_total{miner_id=\"$miner_id\", worker_host=\"$worker_host\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "$worker_host - VMEM (RAM + Swap)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 92 },
   "repeat": "worker_host",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "lotus_miner_worker_vmem_tasks{miner_id=\"$miner_id\", worker_host=\"$worker_host\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "lotus_miner_worker_vmem_reserved{miner_id=\"$miner_id\", worker_host=\"$worker_host\"}",
     "legendFormat": "Reserved"
    },
    {
     "expr": "lotus_miner_worker_vmem_total{miner_id=\"$miner_id\", worker_host=\"$worker_host\"}-lotus_miner_worker_vmem_tasks{miner_id=\"$miner_id\", worker_host=\"$worker_host\"}-lotus_miner_worker_vmem_reserved{miner_id=\"$miner_id\", worker_host=\"$worker_host\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "lotus_miner_worker_vmem_total{miner_id=\"$miner_id\", worker_host=\"$worker_host\"}",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}